name = "CompetingClocks"
uuid = "5bb9b785-358c-4fee-af0f-b94a146244a8"
authors = ["Andrew Dolgert <andrew@dolgert.com>", "Sean L. Wu <slwood@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Combinatorics = "^1.0"
DataStructures = "^0.18"
Distributions = "^0.25"
Documenter = "^1.3"
julia = "^1.8"
Logging = "^1.0"
Random = "^1.0"

[workspace]
projects = ["test", "docs"]
